### ISSUE TITLE
Local website or blank page

### ISSUE THREAD

**Issue by monsieurm** [kevinoes/viewportSize-safari-extension#1]
Hi Kevin

The extension wok fine in MAMP, but doesn't work if the site is local (file:///), or if nothing is displayed in the window.

Great extension, thank you

**Comment by kevinoes** [comment]
Hi monsieurm!

Safari extensions doesn't run on local files. It's Apple's decision :( As far as I know, there's no way to get around this.

**Comment by monsieurm** [comment]
Okay thanks for your answer
